export const PAGE_TITLES = {
  home: 'Home | FamVest App',
  watchlist: 'Watchlist | FamVest App',
  holdings: 'Holdings | FamVest App',
  positions: 'Positions | FamVest App',
  orders: 'Orders | FamVest App',
  basketOrder: 'Basket Order | FamVest App',
  funds: 'Funds | FamVest App',
  mf: 'Mutual Funds | FamVest App',
  algo: 'Algo | FamVest App',
  historicalData: 'Historical Data | FamVest App',
  administration: 'Administration | FamVest App',
  scheduledTasks: 'Scheduled Tasks | FamVest App',
  applicationUsers: 'Application Users | FamVest App',
  ipos: 'IPOs | FamVest App',
  marketHolidays: 'Market Holidays | FamVest App',
  myProfile: 'My Profile | FamVest App',
  login: 'Login | FamVest App',
  signup: 'Signup | FamVest App',
  settings: 'Settings | FamVest App',
  notFound: '404 | Page Not Found',
};
